site_name: AutoDocumentsExample - 
repo_url: https://github.com/markekraus/AutoDocumentsExample
site_author: Mark Kraus
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "AutoDocumentsExample is licensed under the <a href='https://github.com/markekraus/AutoDocumentsExample/raw/master/LICENSE'>MIT license"
pages:
  - Home: index.md